# -*- coding: utf-8 -*-
"""IP address and host name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7USrmixEukCk2dsLxvr2JrUa3tR8__L

# **Get Host Name and Computer IP address in python**
"""

# Importing socket library 

import socket

# Use the function gethostname from socket library

host_name = socket.gethostname()

# Similarly use gethostbyname function to get the IP address


IP_address = socket.gethostbyname(host_name)

# Print the Host Name and IP address


print("Host Name is:" + host_name)
print("Computer IP Address is:" + IP_address)

